CREATE OR REPLACE TRIGGER TRG_KRITIK_STOK
BEFORE INSERT ON STOK_HAREKETI
FOR EACH ROW
WHEN (NEW.HAREKET_TIPI = 'cikis')
DECLARE
    V_STOK   NUMBER;
    V_KRITIK NUMBER;
BEGIN
    SELECT MEVCUT_STOK, KRITIK_STOK_SEVIYE
    INTO V_STOK, V_KRITIK
    FROM URUN
    WHERE URUN_ID = :NEW.URUN_ID;

    IF V_STOK - :NEW.MIKTAR < V_KRITIK THEN
        RAISE_APPLICATION_ERROR(-20001, 'Uyarı: Kritik stok seviyesinin altına düşüldü!');
    END IF;
END;
/